version: '3.9'
services:
  back_container_node:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
  front_container_nuxt:
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"